Traceback (most recent call last):
  File "/main.py", line 129, in <module>
    main()
  File "/main.py", line 94, in main
    player.move_lasers(player.vel, enemies)
  File "\player.py", line 25, in move_lasers
    self.lasers.remove(laser)
ValueError: list.remove(x): x not in list